### ISSUE TITLE
can't use tagcloud and close sidebar of gallery post

### ISSUE THREAD

**Issue by 0bo** [Simpleyyt/jekyll-jacman#12]
I have followed the instruction, and create the index.md in source/tags and source/categories.

in side the index.md, I have tried 

layout: tags
title: tags

but both of them don't work.

could please give a hand? my one is on https://github.com/colingpt/colingpt.github.io

thank you

**Comment by Simpleyyt** [comment]
Sorry. Because the theme is ported from hexo, some instruction is wrong. The correct path is /tags and  /categories (I had created them). And add follow on the _config.yml:

```
menu:
  Home: /
  Categories: /categories
  Tags: /tags
  Archives: /archives
  About: /about
```
