### ISSUE TITLE
无法关闭侧边的TOC

### ISSUE THREAD

**Issue by CodeJuan** [Simpleyyt/jekyll-jacman#4]
- close_aside设置为false
- toc都设置为false

``` yml
close_aside: false  #close sidebar in post page if true

#### Toc
toc:
  article: false   ## show contents in article.
  aside: false     ## show contents in aside.
```

我正在折腾，看能否自己解决。
